### ISSUE TITLE
MongoDB Oct 2019 courses

### ISSUE THREAD

**Issue by pavoldurco** [fecom/mongodb#4]
| Date  | Name | Expected Time  | Real Time  | Description  |
|---|---|---|---|---|
| 10/04/2019 | @fecom @pavoldurco |  1.00 |  2.75 | Introduction | 
| 10/04/2019 | @fecom | 1.00 |  1.00 | #3 Chapter 4 | 
| 10/07/2019 | @pavoldurco | 1.00 #1 Chapter 1 | 2.50  | #1 Chapter 1 | 
| 10/08/2019 | @pavoldurco | 2.50 #1 Chapter 2 | 4.50 | #1 Chapter 2 |
| 10/08/2019 | @pavoldurco | 2.00 #1 Chapter 3 | 1.25 | #1 Chapter 3 |
| 10/17/2019 | @pavoldurco | 0.50 #2 Chapter 0  | 0.50 | #2 Chapter 0 |
| 10/26/2019 | @pavoldurco | 1.50 #3 Chapter 1 | 1.00 | #3 Chapter 1 |
| 10/27/2019 | @pavoldurco | 1.50 #3 Chapter 2 | 1.50 | #3 Chapter 2 |
| 11/05/2019 | @pavoldurco | 2.50 #3 Chapter 3-4 | 3.50 | #3 Chapter 3-4 |

|   |   |   |   |    | 
|---|---|---|---|---|

| Date  | Expected Time | Real Time  | Description  | 
|---|---|---|---|
| 10/2019  | 90 | 3.75 |   | 
| 11/2019  | 70 |  |   | 
|---|---|---|---|
| TOTAL | 160 | 3.75 |   | 
|---|---|---|---|

MongoDB All the courses

**Subtasks:**

**Priority 1:**
- [ ] [#1](https://github.com/fecom/mongodb/issues/1)  M001: MongoDB Basics
- [ ] #2 M220J: MongoDB for Java Developers
- [ ] #3  M320: Data Modeling

**Priority 2:**
- [ ] #5  M121: The MongoDB Aggregation Framework
- [ ] #6 M042: New Features and Tools in MongoDB 4.2

**Priorita 3:**
- [ ] #7 M201: MongoDB Performance
- [ ] #8 M103: Basic Cluster Administration
- [ ] #9 M310: MongoDB Security
- [ ] #10 M312: Diagnostics and Debugging

**Priorita 4:**
- [ ] #11 M220JS: MongoDB for Javascript Developers
- [ ] #12  M220P: MongoDB for Python Developers (e
